
development:
  adapter: postgresql
  encoding: unicode
  database: horario_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: horario_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: horario_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
